config/routes.rb
# == Route Map
#
#                                     Prefix Verb   URI Pattern                                                                Controller#Action
#                                       root GET    /                                                                          static_pages#home
#                          new_admin_session GET    /login(.:format)                                                           devise/sessions#new
#                              admin_session POST   /login(.:format)                                                           devise/sessions#create
#                      destroy_admin_session DELETE /logout(.:format)                                                          devise/sessions#destroy
# commercial_item_collection_collection_item POST   /collections/:collection_id/collection_items/:id/commercial-item(.:format) collection_items#commercial_item
#           image_collection_collection_item POST   /collections/:collection_id/collection_items/:id/image(.:format)           collection_items#image
#                collection_collection_items GET    /collections/:collection_id/collection_items(.:format)                     collection_items#index
#                                            POST   /collections/:collection_id/collection_items(.:format)                     collection_items#create
#             new_collection_collection_item GET    /collections/:collection_id/collection_items/new(.:format)                 collection_items#new
#            edit_collection_collection_item GET    /collections/:collection_id/collection_items/:id/edit(.:format)            collection_items#edit
#                 collection_collection_item GET    /collections/:collection_id/collection_items/:id(.:format)                 collection_items#show
#                                            PATCH  /collections/:collection_id/collection_items/:id(.:format)                 collection_items#update
#                                            PUT    /collections/:collection_id/collection_items/:id(.:format)                 collection_items#update
#                                            DELETE /collections/:collection_id/collection_items/:id(.:format)                 collection_items#destroy
#                                collections GET    /collections(.:format)                                                     collections#index
#                                            POST   /collections(.:format)                                                     collections#create
#                             new_collection GET    /collections/new(.:format)                                                 collections#new
#                            edit_collection GET    /collections/:id/edit(.:format)                                            collections#edit
#                                 collection GET    /collections/:id(.:format)                                                 collections#show
#                                            PATCH  /collections/:id(.:format)                                                 collections#update
#                                            PUT    /collections/:id(.:format)                                                 collections#update
#                                            DELETE /collections/:id(.:format)                                                 collections#destroy
#                              close_enquiry DELETE /enquiries/:id/close(.:format)                                             enquiries#close
#                               open_enquiry POST   /enquiries/:id/open(.:format)                                              enquiries#open
#                          enquiry_responses GET    /enquiries/:enquiry_id/responses(.:format)                                 responses#index
#                                            POST   /enquiries/:enquiry_id/responses(.:format)                                 responses#create
#                       new_enquiry_response GET    /enquiries/:enquiry_id/responses/new(.:format)                             responses#new
#                 enquiry_sale_authorization POST   /enquiries/:enquiry_id/sale_authorization(.:format)                        sale_authorizations#create
#             new_enquiry_sale_authorization GET    /enquiries/:enquiry_id/sale_authorization/new(.:format)                    sale_authorizations#new
#            edit_enquiry_sale_authorization GET    /enquiries/:enquiry_id/sale_authorization/edit(.:format)                   sale_authorizations#edit
#                                            GET    /enquiries/:enquiry_id/sale_authorization(.:format)                        sale_authorizations#show
#                                            PATCH  /enquiries/:enquiry_id/sale_authorization(.:format)                        sale_authorizations#update
#                                            PUT    /enquiries/:enquiry_id/sale_authorization(.:format)                        sale_authorizations#update
#                                            DELETE /enquiries/:enquiry_id/sale_authorization(.:format)                        sale_authorizations#destroy
#                                  enquiries GET    /enquiries(.:format)                                                       enquiries#index
#                                    enquiry GET    /enquiries/:id(.:format)                                                   enquiries#show
#                                 refile_app        /attachments                                                               #<Refile::App app_file="/Users/royaltyclubvp/.rvm/gems/ruby-2.2.3/gems/refile-0.6.2/lib/refile/app.rb">
#

Rails.application.routes.draw do

  root 'static_pages#home'

  devise_for :admins,
             path: '',
             path_names: {
                 sign_in: 'login',
                 sign_out: 'logout'
             }

  resources :collections do
    resources :collection_items do
      member do
        post 'commercial-item', to: 'collection_items#commercial_item'
        post 'image'
      end
    end
  end

  resources :enquiries, only: [:index, :show] do
    member do
      delete 'close'
      post 'open'
    end
    resources :responses, only: [:new, :create, :index]
    resource :sale_authorization, except: [:index]
  end
end

app/models/collection.rb
# == Schema Information
#
# Table name: collections
#
#  id         :integer          not null, primary key
#  name       :string
#  year       :integer
#  slug       :string
#  available  :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_collections_on_slug  (slug) UNIQUE
#

class Collection < ActiveRecord::Base
  # Scopes
  #
  # Available collections
  scope :available, -> { where(available: true) }

  # Attach Friendly URL
  extend FriendlyId
  friendly_id :name, use: :slugged

  # Relationships
  #
  # Contains many ITEMS
  has_many :collection_items, -> {order("created_at asc")},
           inverse_of: :collection,
           dependent: :delete_all

  # Convenience Methods
  #
  # Display 'Yes' or 'No' to represent available attribute
  def published?
    if self.available
      'Yes'
    else
      'No'
    end
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :authenticate_admin!

  # List of Collections
  def index
    @collections = Collection.all
  end

  def show
    @collection = Collection.includes(:collection_items).friendly.find(params[:id])
  end

  # New Collection Form
  def new
    @collection = Collection.new
  end

  # Create Collection
  def create
    collection = Collection.new(collection_params)
    if collection.save
      redirect_to collection_path(collection), success: 'Collection added successfully'
    else
      redirect_to new_collection_path, error: 'Creation of collection failed. Please try again'
    end
  end

  # Edit existing Collection
  def edit
    @collection = Collection.friendly.find(params[:id])
  end

  # Update Collection
  def update
    if Collection.friendly.find(params[:id]).update_attributes(collection_params)
      redirect_to collection_path(params[:id]), success: 'Collection updated'
    else
      redirect_to edit_collection_path(params[:id]), error: 'Updated failed'
    end
  end

  def destroy
    if Collection.friendly.find(params[:id]).destroy
      flash[:success] = 'Collection deleted'
    else
      flash[:error] = 'Deletion failed. Please try again'
    end
    redirect_to collections_path
  end

  private
    def collection_params
      params.require(:collection).permit(:name, :year, :available, :ordered, collection_items_attributes: [:name, :image])
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_collection.html.erb
<tr>
  <td><%= collection.name %></td>
  <td><%= collection.year %></td>
  <td><%= collection.published? %></td>
  <td>
    <div class="btn-group">
      <%= link_to 'View Collection', collection_path(collection), class: 'btn btn-primary', role: 'button' %>
      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="sr-only">Toggle Dropdown</span>
      </button>
      <div class="dropdown-menu">
        <%= link_to 'Add Collection Item', new_collection_collection_item_path(collection), class: 'dropdown-item' %>
        <div class="dropdown-divider"></div>
        <%= link_to 'Edit Collection', edit_collection_path(collection), class: 'dropdown-item' %>
        <%= link_to 'Delete Collection', collection_path(collection), method: :delete, class: 'dropdown-item' %>
      </div>
    </div>
  </td>
</tr>

app/views/collections/edit.html.erb
<% title "Collections - Edit Collection: #{@collection.name}" %>
<% page 'collections-page' %>

<%= link_to 'Cancel', collections_path, class: 'btn btn-danger btn-block', role: 'button' %>

<h1 class="text-xs-center display-3">
  Collections
  <small class="text-muted">Add New Collection</small>
</h1>

<div class="card card-block card-inverse form-card">
  <%= form_for @collection do |f| %>
      <fieldset class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', required: true %>
      </fieldset>

      <fieldset class="form-group">
        <%= f.label :year, 'Collection Year' %>
        <%= f.number_field :year, class: 'form-control', min: 2010 %>
      </fieldset>

      <fieldset class="form-group">
        <label class="c-input c-checkbox">
          <%= f.check_box :available %>
          <span class="c-indicator"></span>
          Publish?
        </label>
      </fieldset>

      <fieldset class="form-group">
        <label class="c-input c-checkbox">
          <%= f.check_box :ordered %>
          <span class="c-indicator"></span>
          Display According to Upload?
        </label>
      </fieldset>

      <%= f.submit 'Save Changes', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/collections/index.html.erb
<% title 'Collections' %>
<% page 'collections-page' %>

<%= link_to 'Add New Collection', new_collection_path, class: 'btn btn-secondary btn-block', role: 'button' %>

<h1 class="text-xs-center display-3">
  Collections
  <small class="text-muted">List of collections</small>
</h1>

<table class="table table-inverse">
  <thead>
    <tr>
      <th>Collection Name</th>
      <th>Collection Year</th>
      <th>Published?</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render(@collections) || content_tag(:tr, content_tag(:td, 'No Collections')) %>
  </tbody>
</table>

app/views/collections/new.html.erb
<% title 'Collections - Add New Collection' %>
<% page 'collections-page' %>

<%= link_to 'Cancel', new_collection_path, class: 'btn btn-danger btn-block', role: 'button' %>

<h1 class="text-xs-center display-3">
  Collections
  <small class="text-muted">Add New Collection</small>
</h1>

<div class="card card-block card-inverse form-card">
  <%= form_for @collection do |f| %>
    <fieldset class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', required: true %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :year, 'Collection Year' %>
      <%= f.number_field :year, class: 'form-control', min: 2010 %>
    </fieldset>

    <fieldset class="form-group">
      <label class="c-input c-checkbox">
        <%= f.check_box :available %>
        <span class="c-indicator"></span>
        Publish?
      </label>
    </fieldset>

    <fieldset class="form-group">
      <label class="c-input c-checkbox">
        <%= f.check_box :ordered %>
        <span class="c-indicator"></span>
        Display According to Upload?
      </label>
    </fieldset>

    <%= f.submit 'Add', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/collections/show.html.erb
<% title "Collections - #{@collection.name}" %>
<% page 'collections-page' %>

<%= link_to 'Back to Collections', collections_path, class: 'btn btn-secondary btn-block', role: 'button' %>
<%= link_to 'Add New Collection Item', new_collection_collection_item_path(@collection), class: 'btn btn-primary btn-block', role: 'button' %>

<h1 class="text-xs-center display-3">
  Collections
  <small class="text-muted"><%= @collection.name %></small>
</h1>

<div class="card-columns" id="collection-items">
  <%= render @collection.collection_items %>
</div>