config/routes.rb
# == Route Map
#
#                                     Prefix Verb   URI Pattern                                                                Controller#Action
#                                       root GET    /                                                                          static_pages#home
#                          new_admin_session GET    /login(.:format)                                                           devise/sessions#new
#                              admin_session POST   /login(.:format)                                                           devise/sessions#create
#                      destroy_admin_session DELETE /logout(.:format)                                                          devise/sessions#destroy
# commercial_item_collection_collection_item POST   /collections/:collection_id/collection_items/:id/commercial-item(.:format) collection_items#commercial_item
#           image_collection_collection_item POST   /collections/:collection_id/collection_items/:id/image(.:format)           collection_items#image
#                collection_collection_items GET    /collections/:collection_id/collection_items(.:format)                     collection_items#index
#                                            POST   /collections/:collection_id/collection_items(.:format)                     collection_items#create
#             new_collection_collection_item GET    /collections/:collection_id/collection_items/new(.:format)                 collection_items#new
#            edit_collection_collection_item GET    /collections/:collection_id/collection_items/:id/edit(.:format)            collection_items#edit
#                 collection_collection_item GET    /collections/:collection_id/collection_items/:id(.:format)                 collection_items#show
#                                            PATCH  /collections/:collection_id/collection_items/:id(.:format)                 collection_items#update
#                                            PUT    /collections/:collection_id/collection_items/:id(.:format)                 collection_items#update
#                                            DELETE /collections/:collection_id/collection_items/:id(.:format)                 collection_items#destroy
#                                collections GET    /collections(.:format)                                                     collections#index
#                                            POST   /collections(.:format)                                                     collections#create
#                             new_collection GET    /collections/new(.:format)                                                 collections#new
#                            edit_collection GET    /collections/:id/edit(.:format)                                            collections#edit
#                                 collection GET    /collections/:id(.:format)                                                 collections#show
#                                            PATCH  /collections/:id(.:format)                                                 collections#update
#                                            PUT    /collections/:id(.:format)                                                 collections#update
#                                            DELETE /collections/:id(.:format)                                                 collections#destroy
#                              close_enquiry DELETE /enquiries/:id/close(.:format)                                             enquiries#close
#                               open_enquiry POST   /enquiries/:id/open(.:format)                                              enquiries#open
#                          enquiry_responses GET    /enquiries/:enquiry_id/responses(.:format)                                 responses#index
#                                            POST   /enquiries/:enquiry_id/responses(.:format)                                 responses#create
#                       new_enquiry_response GET    /enquiries/:enquiry_id/responses/new(.:format)                             responses#new
#                 enquiry_sale_authorization POST   /enquiries/:enquiry_id/sale_authorization(.:format)                        sale_authorizations#create
#             new_enquiry_sale_authorization GET    /enquiries/:enquiry_id/sale_authorization/new(.:format)                    sale_authorizations#new
#            edit_enquiry_sale_authorization GET    /enquiries/:enquiry_id/sale_authorization/edit(.:format)                   sale_authorizations#edit
#                                            GET    /enquiries/:enquiry_id/sale_authorization(.:format)                        sale_authorizations#show
#                                            PATCH  /enquiries/:enquiry_id/sale_authorization(.:format)                        sale_authorizations#update
#                                            PUT    /enquiries/:enquiry_id/sale_authorization(.:format)                        sale_authorizations#update
#                                            DELETE /enquiries/:enquiry_id/sale_authorization(.:format)                        sale_authorizations#destroy
#                                  enquiries GET    /enquiries(.:format)                                                       enquiries#index
#                                    enquiry GET    /enquiries/:id(.:format)                                                   enquiries#show
#                                 refile_app        /attachments                                                               #<Refile::App app_file="/Users/royaltyclubvp/.rvm/gems/ruby-2.2.3/gems/refile-0.6.2/lib/refile/app.rb">
#

Rails.application.routes.draw do

  root 'static_pages#home'

  devise_for :admins,
             path: '',
             path_names: {
                 sign_in: 'login',
                 sign_out: 'logout'
             }

  resources :collections do
    resources :collection_items do
      member do
        post 'commercial-item', to: 'collection_items#commercial_item'
        post 'image'
      end
    end
  end

  resources :enquiries, only: [:index, :show] do
    member do
      delete 'close'
      post 'open'
    end
    resources :responses, only: [:new, :create, :index]
    resource :sale_authorization, except: [:index]
  end
end

app/models/collection_item.rb
# == Schema Information
#
# Table name: collection_items
#
#  id            :integer          not null, primary key
#  name          :string
#  collection_id :integer
#  image_id      :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  slug          :string
#  item_for_sale :boolean          default(FALSE)
#
# Indexes
#
#  index_collection_items_on_collection_id  (collection_id)
#  index_collection_items_on_slug           (slug) UNIQUE
#

class CollectionItem < ActiveRecord::Base
  # File Management
  attachment :image,
             content_type: 'image/jpeg'

  # Attach Friendly URL
  extend FriendlyId
  friendly_id :name, use: :slugged

  # Relationships
  #
  # Is part of a COLLECTION
  belongs_to :collection,
      inverse_of: :collection_items

  # Has received many ENQUIRIES
  has_many :enquiries,
      inverse_of: :collection_item

  # Has many SALE AUTHORIZATIONS
  has_many :sale_authorizations,
           inverse_of: :collection_item

  # Has many ORDERS
  has_many :orders,
      inverse_of: :collection_item
end

app/controllers/collection_items_controller.rb
class CollectionItemsController < ApplicationController
  before_action :authenticate_admin!

  # Add New Collection Items
  def new
    @collection = Collection.friendly.find(params[:collection_id])
  end

  # Create New Item
  def create
    if CollectionItem.create(item_params)
      redirect_to collection_path(params[:collection_id]), success: 'Item added'
    else
      redirect_to collection_path(params[:collection_id]), error: 'Attempt failed'
    end
  end

  # Delete Item
  def destroy
    if CollectionItem.friendly.find(params[:id]).destroy
      flash[:success] = 'Item deleted'
    else
      flash[:error] = 'Deletion failed'
    end
    redirect_to collection_path(params[:collection_id])
  end

  # Set Item as Image
  def image
    if CollectionItem.friendly.find(params[:id]).update_attributes({item_for_sale: false})
      flash[:success] = 'Item set as image'
    else
      flash[:error] = 'Changed failed. Please try again'
    end
    redirect_to collection_path(params[:collection_id])
  end

  def commercial_item
    if CollectionItem.friendly.find(params[:id]).update_attributes({item_for_sale: true})
      flash[:success] = 'Item set for sale'
    else
      flash[:error] = 'Changed failed. Please try again'
    end
    redirect_to collection_path(params[:collection_id])
  end

  private
    def item_params
      params.require(:collection_item).permit(:name, :image, :collection_id, :item_for_sale)
    end
end

app/helpers/collection_items_helper.rb
module CollectionItemsHelper
end

app/views/collection_items/_collection_item.html.erb
<div class="card">
  <%= attachment_image_tag(collection_item, :image, :fit, 640, 650, {alt: collection_item.name, class: 'img-fluid'}) %>
  <div class='card-block text-xs-center'>
    <div class="delete-container">
      <a role="button" class="close" href="<%= collection_collection_item_path(collection_item.collection, collection_item) %>" rel="nofollow" data-method="delete" data-confirm="Are you sure you want to delete this item?" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </a>
    </div>
    <div class="card-block-content">
      <% if collection_item.item_for_sale %>
        <%= link_to 'Set as Image', image_collection_collection_item_path(collection_item.collection, collection_item), class: 'btn btn-primary btn-sm text-xs-center', method: :post %>
      <% else %>
        <%= link_to 'Set for Sale', commercial_item_collection_collection_item_path(collection_item.collection, collection_item), class: 'btn btn-primary btn-sm text-xs-center', method: :post %>
      <% end %>
      <% if collection_item.name.present? %>
        <p class="item-title"><%= collection_item.name %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/collection_items/new.html.erb
<% title 'Collections - Add New Collection Item' %>
<% page 'collections-page' %>

<%= link_to 'Cancel', collections_path, class: 'btn btn-danger btn-block', role: 'button' %>

<h1 class="text-xs-center display-3">
  Collections
  <small class="text-muted">Add New Collection Item</small>
</h1>

<div class="card card-block card-inverse form-card">
  <%= form_for [@collection, @collection.collection_items.new] do |f| %>
      <%= f.hidden_field :collection_id %>
      <fieldset class="form-group">
        <%= f.label :name, 'Item Name (Not required if just image in gallery)' %>
        <%= f.text_field :name, class: 'form-control' %>
      </fieldset>

      <fieldset class="form-group">
        <label class="file">
          <%= f.attachment_field :image, required: true %>
          <span class="file-custom"></span>
        </label>
      </fieldset>

      <fieldset class="form-group">
        <label class="c-input c-checkbox">
          <%= f.check_box :item_for_sale %>
          <span class="c-indicator"></span>
          Item for Sale? (Leave unchecked if just image in gallery)
        </label>
      </fieldset>

      <%= f.submit 'Add Item', class: 'btn btn-primary' %>
  <% end %>
</div>