config/routes.rb
# == Route Map
#
#                                     Prefix Verb   URI Pattern                                                                Controller#Action
#                                       root GET    /                                                                          static_pages#home
#                          new_admin_session GET    /login(.:format)                                                           devise/sessions#new
#                              admin_session POST   /login(.:format)                                                           devise/sessions#create
#                      destroy_admin_session DELETE /logout(.:format)                                                          devise/sessions#destroy
# commercial_item_collection_collection_item POST   /collections/:collection_id/collection_items/:id/commercial-item(.:format) collection_items#commercial_item
#           image_collection_collection_item POST   /collections/:collection_id/collection_items/:id/image(.:format)           collection_items#image
#                collection_collection_items GET    /collections/:collection_id/collection_items(.:format)                     collection_items#index
#                                            POST   /collections/:collection_id/collection_items(.:format)                     collection_items#create
#             new_collection_collection_item GET    /collections/:collection_id/collection_items/new(.:format)                 collection_items#new
#            edit_collection_collection_item GET    /collections/:collection_id/collection_items/:id/edit(.:format)            collection_items#edit
#                 collection_collection_item GET    /collections/:collection_id/collection_items/:id(.:format)                 collection_items#show
#                                            PATCH  /collections/:collection_id/collection_items/:id(.:format)                 collection_items#update
#                                            PUT    /collections/:collection_id/collection_items/:id(.:format)                 collection_items#update
#                                            DELETE /collections/:collection_id/collection_items/:id(.:format)                 collection_items#destroy
#                                collections GET    /collections(.:format)                                                     collections#index
#                                            POST   /collections(.:format)                                                     collections#create
#                             new_collection GET    /collections/new(.:format)                                                 collections#new
#                            edit_collection GET    /collections/:id/edit(.:format)                                            collections#edit
#                                 collection GET    /collections/:id(.:format)                                                 collections#show
#                                            PATCH  /collections/:id(.:format)                                                 collections#update
#                                            PUT    /collections/:id(.:format)                                                 collections#update
#                                            DELETE /collections/:id(.:format)                                                 collections#destroy
#                              close_enquiry DELETE /enquiries/:id/close(.:format)                                             enquiries#close
#                               open_enquiry POST   /enquiries/:id/open(.:format)                                              enquiries#open
#                          enquiry_responses GET    /enquiries/:enquiry_id/responses(.:format)                                 responses#index
#                                            POST   /enquiries/:enquiry_id/responses(.:format)                                 responses#create
#                       new_enquiry_response GET    /enquiries/:enquiry_id/responses/new(.:format)                             responses#new
#                 enquiry_sale_authorization POST   /enquiries/:enquiry_id/sale_authorization(.:format)                        sale_authorizations#create
#             new_enquiry_sale_authorization GET    /enquiries/:enquiry_id/sale_authorization/new(.:format)                    sale_authorizations#new
#            edit_enquiry_sale_authorization GET    /enquiries/:enquiry_id/sale_authorization/edit(.:format)                   sale_authorizations#edit
#                                            GET    /enquiries/:enquiry_id/sale_authorization(.:format)                        sale_authorizations#show
#                                            PATCH  /enquiries/:enquiry_id/sale_authorization(.:format)                        sale_authorizations#update
#                                            PUT    /enquiries/:enquiry_id/sale_authorization(.:format)                        sale_authorizations#update
#                                            DELETE /enquiries/:enquiry_id/sale_authorization(.:format)                        sale_authorizations#destroy
#                                  enquiries GET    /enquiries(.:format)                                                       enquiries#index
#                                    enquiry GET    /enquiries/:id(.:format)                                                   enquiries#show
#                                 refile_app        /attachments                                                               #<Refile::App app_file="/Users/royaltyclubvp/.rvm/gems/ruby-2.2.3/gems/refile-0.6.2/lib/refile/app.rb">
#

Rails.application.routes.draw do

  root 'static_pages#home'

  devise_for :admins,
             path: '',
             path_names: {
                 sign_in: 'login',
                 sign_out: 'logout'
             }

  resources :collections do
    resources :collection_items do
      member do
        post 'commercial-item', to: 'collection_items#commercial_item'
        post 'image'
      end
    end
  end

  resources :enquiries, only: [:index, :show] do
    member do
      delete 'close'
      post 'open'
    end
    resources :responses, only: [:new, :create, :index]
    resource :sale_authorization, except: [:index]
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :authenticate_admin!

  # List Message Thread
  def index
    @enquiry = Enquiry.includes(:user, :responses).find(params[:enquiry_id])
  end

  # Write new RESPONSE
  def new
    @enquiry = Enquiry.includes(:user, :responses).find(params[:enquiry_id])
  end

  # Save RESPONSE
  def create
    response = Response.new(response_params)
    response.writer = current_admin
    if response.save
      redirect_to enquiry_responses_path(params[:enquiry_id]), success: 'Response sent'
    else
      redirect_to new_enquiry_response_path(params[:enquiry_id]), error: 'Sending failed'
    end
  end

  private

    def response_params
      params.require(:response).permit(:message, :enquiry_id)
    end
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/_enquiry.html.erb
<li class="list-group-item active">
  <h6 class="list-group-item-heading"><%= enquiry.user.name %>:</h6>
  <p class="list-group-item-text"><%= enquiry.message %></p>
</li>

app/views/responses/_response.html.erb
<% if response.writer.name == 'Admin'
     writer_name = 'You'
   else
     writer_name = response.writer.name
   end
%>

<li class="list-group-item">
  <h6 class="list-group-item-heading"><%= writer_name %>:</h6>
  <p class="list-group-item-text"><%= response.message %></p>
</li>

app/views/responses/index.html.erb
<% title "Enquiry from #{@enquiry.user.name}" %>
<% page 'responses-page' %>

<%= link_to 'Back to Enquiries', enquiries_path, class: 'btn btn-secondary btn-block', role: 'button' %>
<%= link_to 'Add Response', new_enquiry_response_path(@enquiry), class: 'btn btn-primary btn-block', role: 'button' %>

<h1 class="text-xs-center display-3">
  Enquiry
  <small class="text-muted">From <%= @enquiry.user.name %> | Re: <%= @enquiry.collection_item.name %></small>
</h1>

<div class="list-group">
  <%= render(partial: 'enquiry', object: @enquiry) if @enquiry.message.present? %>
  <%= render @enquiry.responses.order(created_at: :asc) %>
</div>

app/views/responses/new.html.erb
<% title "Enquiry from #{@enquiry.user.name} - New Response" %>
<% page 'responses-page' %>

<%= link_to 'Back to Enquiries', enquiries_path, class: 'btn btn-secondary btn-block', role: 'button' %>

<h1 class="text-xs-center display-3">
  Enquiry
  <small class="text-muted">From <%= @enquiry.user.name %> | Re: <%= @enquiry.collection_item.name %></small>
</h1>

<div class="card mx-auto" id="messages-card">
  <div class="card-header">
    Write your response
  </div>
  <div class="card-block">
    <%= form_for [@enquiry, @enquiry.responses.new] do |f| %>
      <%= f.hidden_field :enquiry_id %>
      <fieldset class="form-group">
        <%= f.label :message %>
        <%= f.text_area :message, class: 'form-control', required: true %>
      </fieldset>

      <%= f.submit 'Send', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

<div class="list-group">
  <%= render @enquiry.responses.order(created_at: :desc) %>
  <%= render(partial: 'enquiry', object: @enquiry) if @enquiry.message.present? %>
</div>