config/routes.rb
# == Route Map
#
#                                     Prefix Verb   URI Pattern                                                                Controller#Action
#                                       root GET    /                                                                          static_pages#home
#                          new_admin_session GET    /login(.:format)                                                           devise/sessions#new
#                              admin_session POST   /login(.:format)                                                           devise/sessions#create
#                      destroy_admin_session DELETE /logout(.:format)                                                          devise/sessions#destroy
# commercial_item_collection_collection_item POST   /collections/:collection_id/collection_items/:id/commercial-item(.:format) collection_items#commercial_item
#           image_collection_collection_item POST   /collections/:collection_id/collection_items/:id/image(.:format)           collection_items#image
#                collection_collection_items GET    /collections/:collection_id/collection_items(.:format)                     collection_items#index
#                                            POST   /collections/:collection_id/collection_items(.:format)                     collection_items#create
#             new_collection_collection_item GET    /collections/:collection_id/collection_items/new(.:format)                 collection_items#new
#            edit_collection_collection_item GET    /collections/:collection_id/collection_items/:id/edit(.:format)            collection_items#edit
#                 collection_collection_item GET    /collections/:collection_id/collection_items/:id(.:format)                 collection_items#show
#                                            PATCH  /collections/:collection_id/collection_items/:id(.:format)                 collection_items#update
#                                            PUT    /collections/:collection_id/collection_items/:id(.:format)                 collection_items#update
#                                            DELETE /collections/:collection_id/collection_items/:id(.:format)                 collection_items#destroy
#                                collections GET    /collections(.:format)                                                     collections#index
#                                            POST   /collections(.:format)                                                     collections#create
#                             new_collection GET    /collections/new(.:format)                                                 collections#new
#                            edit_collection GET    /collections/:id/edit(.:format)                                            collections#edit
#                                 collection GET    /collections/:id(.:format)                                                 collections#show
#                                            PATCH  /collections/:id(.:format)                                                 collections#update
#                                            PUT    /collections/:id(.:format)                                                 collections#update
#                                            DELETE /collections/:id(.:format)                                                 collections#destroy
#                              close_enquiry DELETE /enquiries/:id/close(.:format)                                             enquiries#close
#                               open_enquiry POST   /enquiries/:id/open(.:format)                                              enquiries#open
#                          enquiry_responses GET    /enquiries/:enquiry_id/responses(.:format)                                 responses#index
#                                            POST   /enquiries/:enquiry_id/responses(.:format)                                 responses#create
#                       new_enquiry_response GET    /enquiries/:enquiry_id/responses/new(.:format)                             responses#new
#                 enquiry_sale_authorization POST   /enquiries/:enquiry_id/sale_authorization(.:format)                        sale_authorizations#create
#             new_enquiry_sale_authorization GET    /enquiries/:enquiry_id/sale_authorization/new(.:format)                    sale_authorizations#new
#            edit_enquiry_sale_authorization GET    /enquiries/:enquiry_id/sale_authorization/edit(.:format)                   sale_authorizations#edit
#                                            GET    /enquiries/:enquiry_id/sale_authorization(.:format)                        sale_authorizations#show
#                                            PATCH  /enquiries/:enquiry_id/sale_authorization(.:format)                        sale_authorizations#update
#                                            PUT    /enquiries/:enquiry_id/sale_authorization(.:format)                        sale_authorizations#update
#                                            DELETE /enquiries/:enquiry_id/sale_authorization(.:format)                        sale_authorizations#destroy
#                                  enquiries GET    /enquiries(.:format)                                                       enquiries#index
#                                    enquiry GET    /enquiries/:id(.:format)                                                   enquiries#show
#                                 refile_app        /attachments                                                               #<Refile::App app_file="/Users/royaltyclubvp/.rvm/gems/ruby-2.2.3/gems/refile-0.6.2/lib/refile/app.rb">
#

Rails.application.routes.draw do

  root 'static_pages#home'

  devise_for :admins,
             path: '',
             path_names: {
                 sign_in: 'login',
                 sign_out: 'logout'
             }

  resources :collections do
    resources :collection_items do
      member do
        post 'commercial-item', to: 'collection_items#commercial_item'
        post 'image'
      end
    end
  end

  resources :enquiries, only: [:index, :show] do
    member do
      delete 'close'
      post 'open'
    end
    resources :responses, only: [:new, :create, :index]
    resource :sale_authorization, except: [:index]
  end
end

app/models/enquiry.rb
# == Schema Information
#
# Table name: enquiries
#
#  id                 :integer          not null, primary key
#  collection_item_id :integer
#  user_id            :integer
#  message            :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  status             :integer          default(0)
#
# Indexes
#
#  index_enquiries_on_collection_item_id  (collection_item_id)
#  index_enquiries_on_user_id             (user_id)
#

class Enquiry < ActiveRecord::Base
  # Set status as enum
  enum status: %i(opened authorized closed)

  # Relationships
  #
  # Has many RESPONSES
  has_many :responses, inverse_of: :enquiry

  # Sent by a USER
  belongs_to :user, inverse_of: :enquiries

  # Related to a COLLECTION_ITEM
  belongs_to :collection_item, inverse_of: :enquiries

  # May have one SALE AUTHORIZATION
  has_one :sale_authorization, inverse_of: :enquiry
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  before_action :authenticate_admin!

  # Show all ENQUIRIES
  def index
    @enquiries = Enquiry.includes(:user, collection_item: :collection).all
  end

  # Show Enquiry Details
  def show
    @enquiry = Enquiry.includes(:user, collection_item: :collection).find(params[:id])
  end

  # Close Enquiry
  def close
    if Enquiry.find(params[:id]).closed!
      flash[:success] = 'Enquiry closed'
    else
      flash[:error] = 'Closing of enquiry failed'
    end
    redirect_to enquiries_path
  end

  # Open  Enquiry
  def open
    if Enquiry.find(params[:id]).opened!
      flash[:success] = 'Enquiry opened'
    else
      flash[:error] = 'Opening of enquiry failed'
    end
    redirect_to enquiries_path
  end
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/views/enquiries/_authorized_enquiry.html.erb
<tr>
  <td><%= authorized_enquiry.created_at.strftime('%d/%m/%Y') %></td>
  <td><%= authorized_enquiry.user.name %></td>
  <td><%= authorized_enquiry.collection_item.collection.name %> - <%= authorized_enquiry.collection_item.name %></td>
  <td><%= authorized_enquiry.sale_authorization.created_at.strftime('%d/%m/%Y') %></td>
  <td>
    <div class="btn-group">
      <%= link_to 'Cancel Authorization', enquiry_sale_authorization_path(authorized_enquiry), method: :delete, class: 'btn btn-danger', role: 'button' %>
      <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="sr-only">Toggle Dropdown</span>
      </button>
      <div class="dropdown-menu">
        <%= link_to 'Edit Authorization', edit_enquiry_sale_authorization_path(authorized_enquiry), class: 'dropdown-item' %>
      </div>
    </div>
  </td>
</tr>

app/views/enquiries/_closed_enquiry.html.erb
<tr>
  <td><%= closed_enquiry.created_at.strftime('%d/%m/%Y') %></td>
  <td><%= closed_enquiry.user.name %></td>
  <td><%= closed_enquiry.collection_item.collection.name %> - <%= closed_enquiry.collection_item.name %></td>
  <td>
    <% if closed_enquiry.message.present? or (closed_enquiry.responses.count. > 0) %>
      <div class="btn-group">
        <%= link_to 'Open Enquiry', open_enquiry_path(closed_enquiry), class: 'btn btn-primary', role: 'button', method: :post %>
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <div class="dropdown-menu">
          <% if closed_enquiry.message.present? -%>
            <%= link_to 'View Enquiry Message', enquiry_path(closed_enquiry), class: 'dropdown-item' %>
          <% end -%>
          <% if closed_enquiry.responses.count > 0 -%>
            <%= link_to 'View Message Thread', '#', class: 'dropdown-item' %>
          <% end -%>
        </div>
      </div>
    <% else %>
      <%= link_to 'Open Enquiry', open_enquiry_path(closed_enquiry), class: 'btn btn-primary', role: 'button', method: :post %>
    <% end %>
  </td>
</tr>

app/views/enquiries/_open_enquiry.html.erb
<tr>
  <td><%= open_enquiry.created_at.strftime('%d/%m/%Y') %></td>
  <td><%= open_enquiry.user.name %></td>
  <td><%= open_enquiry.collection_item.collection.name %> - <%= open_enquiry.collection_item.name %></td>
  <td>
    <div class="btn-group">
      <% if open_enquiry.message.present? %>
        <%= link_to 'View Enquiry', enquiry_path(open_enquiry), class: 'btn btn-primary', role: 'button' %>
      <% else %>
        <%= link_to 'Respond to Enquiry', new_enquiry_response_path(open_enquiry), class: 'btn btn-primary', role: 'button' %>
      <% end %>
      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="sr-only">Toggle Dropdown</span>
      </button>
      <div class="dropdown-menu">
        <% if open_enquiry.message.present? %>
            <%= link_to 'Respond to Enquiry', new_enquiry_response_path(open_enquiry), class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
        <% end %>
        <% if open_enquiry.responses.count > 0 %>
            <%= link_to 'View Message Thread', enquiry_responses_path(open_enquiry), class: 'dropdown-item' %>
        <% end %>
        <%= link_to 'Authorize Sale', new_enquiry_sale_authorization_path(open_enquiry), class: 'dropdown-item' %>
        <%= link_to 'Close Enquiry', close_enquiry_path(open_enquiry), class: 'dropdown-item', method: :delete %>
      </div>
    </div>
  </td>
</tr>

app/views/enquiries/index.html.erb
<% title 'Enquiries' %>
<% page 'enquiries-page' %>

<h1 class="text-xs-center display-3">
  Enquiries
  <small class="text-muted">List of enquiries</small>
</h1>

<% opened = "
  <table class='table'>
    <thead class='thead-inverse'>
      <tr>
        <th>Date</th>
        <th>Enquirer</th>
        <th>Item</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      #{render(partial: 'enquiries/open_enquiry', collection: @enquiries.opened) || content_tag(:tr, content_tag(:td, 'No Enquiries'))}
    </tbody>
  </table>
".html_safe

authorized = "
  <table class='table'>
    <thead class='thead-inverse'>
      <tr>
        <th>Date</th>
        <th>Enquirer</th>
        <th>Item</th>
        <th>Date of Authorization</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      #{render(partial: 'enquiries/authorized_enquiry', collection: @enquiries.authorized) || content_tag(:tr, content_tag(:td, 'No Authorized Enquiries'))}
    </tbody>
  </table>
".html_safe

closed = "
  <table class='table'>
    <thead class='thead-inverse'>
      <tr>
        <th>Date</th>
        <th>Enquirer</th>
        <th>Item</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      #{render(partial: 'enquiries/closed_enquiry', collection: @enquiries.closed) || content_tag(:tr, content_tag(:td, 'No Enquiries'))}
    </tbody>
  </table>
".html_safe

tabs = {:open => opened, :authorized => authorized, :closed => closed}
%>

<!-- Create Tabs with Tab Helper -->
<%= tabs_for(tabs) %>

app/views/enquiries/show.html.erb
<% title "Enquiry from #{@enquiry.user.name}" %>
<% page 'enquiries-page' %>

<%= link_to 'Back to Enquiries', enquiries_path, class: 'btn btn-secondary btn-block', role: 'button' %>
<%= link_to 'Add Response', new_enquiry_response_path(@enquiry), class: 'btn btn-primary btn-block', role: 'button' %>

<h1 class="text-xs-center display-3">
  Enquiry
</h1>

<div class="card mx-auto" id="messages-card">
  <div class="card-header">
    <h5><%= @enquiry.collection_item.collection.name + ' - ' + @enquiry.collection_item.name %></h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <p><strong>From: </strong><%= @enquiry.user.name %></p>
    </li>
    <li class="list-group-item">
      <p><strong>Date: </strong><%= @enquiry.created_at.strftime('%d/%m/%Y') %></p>
    </li>
  </ul>
  <div class="card-block">
    <p><%= @enquiry.message %></p>
  </div>
</div>